-- This is the main entrypoint for your schema.
-- It is used to control the order in which schemas are included.
--
-- Imports can be performed using the following syntax where paths are relative from the current file.
-- `-- housekeeper:import <path>.sql`.
--
-- There is no requirement to follow a convention for schema layout, but typically your db folder will look like the
-- following:
--
-- db/main.sql (this file)
--   -- housekeeper:import schemas/[DATABASE]/db.sql
-- db/migrations/
--   [ENV]/
--     [TIMESTAMP].sql (auto-generated migrations)
--     housekeeper.sum (checksums for migrations)
-- db/schemas/
--   [DATABASE]
--     schema.sql
--       -- housekeeper:import tables/[TABLE].sql
--     dictionaries/
--     tables/
--       [TABLE].sql
--     views/

-- Import housekeeper system database (for migration tracking)
-- housekeeper:import schemas/housekeeper/housekeeper.sql

