-- This is the main entrypoint for your schema.
-- It is used to control the order in which schemas are included.
--
-- Imports can be performed using the following syntax where paths are relative from the current file.
-- `-- housekeeper:import <path>.sql`.
--
-- There is no requirement to follow a convention for schema layout, but typically your db folder will look like the
-- following:
--
-- db/main.sql (this file)
--   -- housekeeper:import schemas/_global/roles/main.sql
--   -- housekeeper:import schemas/[DATABASE]/db.sql
-- db/migrations/
--   [TIMESTAMP].sql (auto-generated migrations)
--   housekeeper.sum (checksums for migrations)
-- db/schemas/
--   _global/
--     roles/ (global cluster-wide roles)
--       main.sql
--       [ROLE_NAME].sql (individual role definitions)
--     collections/ (future: global named collections)
--     users/ (future: global user definitions)
--   [DATABASE]
--     schema.sql
--       -- housekeeper:import collections/[COLLECTION].sql
--       -- housekeeper:import tables/[TABLE].sql
--     collections/
--       [COLLECTION].sql
--     dictionaries/
--     tables/
--       [TABLE].sql
--     views/
--
-- Import global objects first (roles, users, settings profiles, etc.)
-- housekeeper:import schemas/_global/roles/main.sql
